package TS_011CHECKOUT_FUNCTIONALITY;

import org.openqa.selenium.By;
import org.testng.annotations.Test;

import TS_008_ADD_TO_CART_FUNCTIONALITY.TC_ATC_001_ADD_TO_CART_FUNCTIONALITY;
import TS_010_SHOPPING_CART_FUNCTIONALITY.TC_SC_002_SHOPPINGCART_FUNCTIONALITY2;
import TS_010_SHOPPING_CART_FUNCTIONALITY.TC_SC_009_SHOPPINGCART_FUNCTIONALITY3;

public class TC_CO_004_CHECKOUT_FUNCTIONALITY4 extends TC_ATC_001_ADD_TO_CART_FUNCTIONALITY {
	@Test
	public void existing_address_checkout() {
		TC_CO_004_CHECKOUT_FUNCTIONALITY4 c_O_001 = new TC_CO_004_CHECKOUT_FUNCTIONALITY4();
		c_O_001.checkout_page();

	}
}
